In [1]:
# Obtain Eigen values and Eigen vector for the given matrix
# |1  -3  3|
# |3  -5  3|
# |6  -6  4|
import numpy as np 
I = np.array([[1,-3,3], [3,-5,3], [6,-6,4]])
print("\n Given matrix: \n", I)
w,v = np.linalg.eig(I)
print("\n Eigen values: \n", w)
print("\n Eigen vectors: \n", v)


 Given matrix: 
 [[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]

 Eigen values: 
 [ 4. -2. -2.]

 Eigen vectors: 
 [[-0.40824829 -0.40824829 -0.1846118 ]
 [-0.40824829  0.40824829 -0.78110113]
 [-0.81649658  0.81649658 -0.59648932]]
