In [ ]:
# Obtain Eigen values and Eigen vector for the given matrix
# |1  -3  3|
# |3  -5  3|
# |6  -6  4|
import numpy as np 
I = np.array([[1,-3,3], [3,-5,3], [6,-6,4]])
print("\n Given matrix: \n", I)
w,v = np.linalg.eig(I)
print("\n Eigen values: \n", w)
print("\n Eigen vectors: \n", v)


 Given matrix: 
 [[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]

 Eigen values: 
 [ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j]

 Eigen vectors: 
 [[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]
