In [6]:
# Obtain Eigen values and Eigen vector for the given matrix
# |4  3  2|
# |1  4  1|
# |3  10 4|
import numpy as np
I = np.array([[4,3,2], [1,4,1], [3,10,4]])
print("\n Given matrix: \n", I)
w,v = np.linalg.eig(I)
print("\n Eigen values: \n", w)
print("\n Eigen vectors: \n", v)
print("\n Eigen value:\n", w[0])
print("\n Corresponding Eigen vector : ", v[:,0])


 Given matrix: 
 [[ 4  3  2]
 [ 1  4  1]
 [ 3 10  4]]

 Eigen values: 
 [8.98205672 2.12891771 0.88902557]

 Eigen vectors: 
 [[-0.49247712 -0.82039552 -0.42973429]
 [-0.26523242  0.14250681 -0.14817858]
 [-0.82892584  0.55375355  0.89071407]]

 Eigen value:
 8.982056720677654

 Corresponding Eigen vector :  [-0.49247712 -0.26523242 -0.82892584]
